services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      args:
        DATABASE_URL: postgresql://admin:password@postgres:5432/test
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/test
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: